export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const CREATE_ORDER = 'CREATE_ORDER';
export const GET_ORDERS = 'GET_ORDERS';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const DELETE_ORDER = 'DELETE_ORDER';